name: Java CI

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish Maven Library
        env:
          USERNAME: d.kurata.38@gmail.com
          PASSWORD: ${{ secrets.MAVEN_DEPLOY_TOKEN }}
        uses: docker://openjdk:11
        with:
          args: "./gradlew publish"
